// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client';

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type HomeDocumentDataSlicesSlice = MeinfoSlice;

/**
 * Content for home documents
 */
interface HomeDocumentData {
	/**
	 * Titel field in *home*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: home.titel
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	titel: prismic.RichTextField;

	/**
	 * Slice Zone field in *home*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: home.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<HomeDocumentDataSlicesSlice>
	/**
	 * Meta Description field in *home*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: home.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */;
	meta_description: prismic.KeyTextField;

	/**
	 * Meta Image field in *home*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: home.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	meta_image: prismic.ImageField<never>;

	/**
	 * Meta Title field in *home*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: home.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	meta_title: prismic.KeyTextField;
}

/**
 * home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
	Simplify<HomeDocumentData>,
	'home',
	Lang
>;

export type AllDocumentTypes = HomeDocument;

/**
 * Primary content in *Meinfo → Primary*
 */
export interface MeinfoSliceDefaultPrimary {
	/**
	 * naam field in *Meinfo → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: meinfo.primary.naam
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	naam: prismic.RichTextField;

	/**
	 * image field in *Meinfo → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: meinfo.primary.image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;

	/**
	 * text field in *Meinfo → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: meinfo.primary.text
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	text: prismic.RichTextField;

	/**
	 * text2 field in *Meinfo → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: meinfo.primary.text2
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	text2: prismic.RichTextField;

	/**
	 * text3 field in *Meinfo → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: meinfo.primary.text3
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	text3: prismic.RichTextField;
}

/**
 * Default variation for Meinfo Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MeinfoSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<MeinfoSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *Meinfo*
 */
type MeinfoSliceVariation = MeinfoSliceDefault;

/**
 * Meinfo Shared Slice
 *
 * - **API ID**: `meinfo`
 * - **Description**: Meinfo
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MeinfoSlice = prismic.SharedSlice<'meinfo', MeinfoSliceVariation>;

declare module '@prismicio/client' {
	interface CreateClient {
		(
			repositoryNameOrEndpoint: string,
			options?: prismic.ClientConfig
		): prismic.Client<AllDocumentTypes>;
	}

	namespace Content {
		export type {
			HomeDocument,
			HomeDocumentData,
			HomeDocumentDataSlicesSlice,
			AllDocumentTypes,
			MeinfoSlice,
			MeinfoSliceDefaultPrimary,
			MeinfoSliceVariation,
			MeinfoSliceDefault
		};
	}
}
